steps:
- name: 'python:3.7-slim'
  entrypoint: /bin/sh
  id: test
  args: [-c, 'pip install -r requirements.txt && python sample_http_test.py -v']

# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - functions
#   - deploy
#   - hello_get
#   - --source=.
#   - --trigger-http
#   - --runtime=python37
#   - --allow-unauthenticated
